### ISSUE TITLE
VM Agent Storage Account not being provisioned with 'jenkinsconfig' container anymore

### ISSUE THREAD

**Issue by ryanberger-az** [jenkinsci/azure-vm-agents-plugin#288]
Hi,

I am noticing an issue with storage account creation for VM Agent templates. When not using an existing storage account, leaving that field blank will trigger the Azure VM Agent plugin to create a new storage account. **This is working.** Where the issue lies, is that normally it also creates a blob container inside of the storage account named jenkinsconfig. This is where initialization scripts that are configured in the VM Agent template are wrapped into a .ps1 file, and stored here for customScriptExtension execution during the agents being created via ARM template.

![image](https://user-images.githubusercontent.com/60238330/122283147-3e561580-ceba-11eb-9cee-f22d34f338bf.png)

This container is no longer being automatically created when a new storage account is created. When I go in and MANUALLY create the container, it starts working again. The error from the Jenkins sys log is:

**AzureVMManagementServiceDelegate: getCloudBlobContainer: unable to get CloudStorageAccount with container name jenkinsconfig**

This is an issue for us as we deploy a Jenkins stack with a fully automated Azure configuration, and normally this was working out of the box and allowed us to fully automate the deployment + provisioning of an agent VM via JCasC.

The plugins we install:
      blueocean:latest
      timestamper:latest
      ws-cleanup:latest
      subversion:latest
      ssh-slaves:latest
      email-ext:latest
      gradle:latest
      azure-vm-agents:latest
      azure-container-agents:latest
      windows-azure-storage:latest
      azure-credentials:latest
      azure-acs:latest
      cloud-stats:latest
      configuration-as-code:latest
      git:latest
      pipeline-github-lib:latest
      github-branch-source:latest
      pipeline-stage-view:latest
      build-pipeline-plugin:latest
      workflow-aggregator:latest
      azure-artifact-manager:latest
      http_request:latest

**Comment by ryanberger-az** [comment]
@timja per your request - thanks again!

**Comment by timja** [comment]
Hey I tried to reproduce this and wasn't able to.

My agent didn't end up connecting but something must've been wrong in the script, I haven't tried connecting an inbound agent before with this plugin

I used a new storage account and it created the account, container and uploaded the PS1 file just fine.

Are you able to share your config? redacting whatever you need


```yaml
jenkins:
  clouds:
    - azureVM:
        azureCredentialsId: "charmander"
        cloudName: "issue-288"
        deploymentTimeout: 1200
        existingResourceGroupName: "tim-azure-vm-agents"
        maxVirtualMachinesLimit: 10
        resourceGroupReferenceType: "existing"
        vmTemplates:
          - agentLaunchMethod: "JNLP"
            agentWorkspace: "C:\\Jenkins"
            builtInImage: "Windows Server 2019"
            credentialsId: "vm-agents-password"
            diskType: "managed"
            doNotUseMachineIfInitFails: true
            enableMSI: false
            enableUAMI: false
            ephemeralOSDisk: false
            executeInitScriptAsRoot: false
            existingStorageAccountName: "timtestvmagentsssd"
            imageReference:
              offer: "WindowsServer"
              publisher: "MicrosoftWindowsServer"
              sku: "2019-Datacenter"
              version: "latest"
            imageTopLevelType: "advanced"
            initScript: |
              Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

              choco install -y adoptopenjdk11

              $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

              java -version

              # Install Maven

              choco install -y maven

              $env:M2_HOME = [System.Environment]::GetEnvironmentVariable("M2_HOME","Machine")
              $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

              mvn --version

              # Install Git

              choco install -y git

              $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

              #Disable git credential manager, get more details in https://support.cloudbees.com/hc/en-us/articles/221046888-Build-Hang-or-Fail-with-Git-for-Windows
              git config --system --unset credential.helper

              git --version

              # Setup inbound agent

              $jenkinsserverurl = $args[0]
              $vmname = $args[1]
              $secret = $args[2]

              # Downloading jenkins agent jar
              Write-Output "Downloading jenkins agent jar "
              $slaveSource = $jenkinsserverurl + "jnlpJars/agent.jar"
              $destSource = "C:\agent.jar"
              $wc = New-Object System.Net.WebClient
              $wc.DownloadFile($slaveSource, $destSource)

              # execute agent
              Write-Output "Executing agent process "
              $java="java"
              $jar="-jar"
              $jenkinsHost=******.ngrok.io:******
              $serverURL=$jenkinsserverurl + "computer/" + $vmname + '/jenkins-agent.jnlp'

              $instanceIdentity="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzFVRE4Ak5Xzll7qjr1UqX6cyOEOsOfmBW5Vc8Vgm4HnCW/3tdCX/vxgbHPwwccDUpSvwWaqPtfFBi8t6ZQAW797BiJ5iFN48RGXnyquI5YR5GydbyBVQLAgRNJMLIrDpdVWK2+VN/qCaG+NdfioVPWmNm+N5/gvQAixvsXSiNwxks/yfBUAFeOigHjBXZJa02R8wU/FQUDEtcF7Eqh1W6gajnNzpjez4vhck2bs/7O3h5Grc47VKc3s3IIoL5AywjrpASb2kuBopYvFdOoSPhQH+pOYFaKrG4ExFnzzgjL319hE54mpxlvHX4WBlvRi2jt4u5Cj+Z/MTrOSwKd63qQIDAQAB"

              # TODO look at porting the run as service part of the old script from https://raw.githubusercontent.com/Azure/jenkins/master/agents_scripts/Jenkins-Windows-Init-Script-Jnlp.ps1
              while ($true) {
                try {
                  # Launch
                  & java -cp agent.jar hudson.remoting.jnlp.Main -headless -direct $jenkinsHost -instanceIdentity $instanceIdentity -workDir "C:\Jenkins" $secret $vmname

                }
                catch [System.Exception] {
                  Write-Output $_.Exception.ToString()
                }
                Start-Sleep 10
              }
            installDocker: false
            installGit: false
            installMaven: false
            javaPath: "java"
            labels: "windows-288"
            location: "UK South"
            maximumDeploymentSize: 10
            newStorageAccountName: "jnoferzzhwy5wvz5fpobriew"
            noOfParallelJobs: 1
            osDiskSize: 0
            osType: "Windows"
            preInstallSsh: false
            retentionStrategy:
              azureVMCloudRetentionStrategy:
                idleTerminationMinutes: 60
            shutdownOnIdle: false
            storageAccountNameReferenceType: "new"
            storageAccountType: "Standard_LRS"
            templateDisabled: false
            templateName: "issue288"
            usageMode: "Use this node as much as possible"
            usePrivateIP: false
            virtualMachineSize: "Standard_B8ms"
```

**Comment by camerenisonfire** [comment]
Here is the log and strack trace from Jenkins when this error occurs:
```Jun 17, 2021 12:18:24 PM INFO com.azure.core.util.logging.ClientLogger performLogging
Azure Identity => getToken() result for scopes [https://management.core.windows.net//.default]: SUCCESS
Jun 17, 2021 12:18:24 PM INFO com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate getCloudStorageAccount
AzureVMManagementServiceDelegate: getCloudStorageAccount: the suffix for construct CloudStorageCloud is https://jnwgdvoq84jnrcgbhcprw5mw.blob.core.windows.net/
Jun 17, 2021 12:18:24 PM SEVERE com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate getCloudBlobContainer
AzureVMManagementServiceDelegate: getCloudBlobContainer: unable to get CloudStorageAccount with container name jenkinsconfig
Jun 17, 2021 12:18:24 PM SEVERE com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate createDeployment
AzureVMManagementServiceDelegate: deployment: Unable to deploy
Also:   java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1703)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:128)
		at com.azure.storage.blob.BlobContainerClient.existsWithResponse(BlobContainerClient.java:228)
		at com.azure.storage.blob.BlobContainerClient.exists(BlobContainerClient.java:211)
		at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.getCloudBlobContainer(AzureVMManagementServiceDelegate.java:2619)
		at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.getCloudBlobContainer(AzureVMManagementServiceDelegate.java:2645)
		at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.uploadCustomScript(AzureVMManagementServiceDelegate.java:863)
		at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.createDeployment(AzureVMManagementServiceDelegate.java:516)
		at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.createDeployment(AzureVMManagementServiceDelegate.java:190)
		at com.microsoft.azure.vmagent.AzureVMAgentTemplate.provisionAgents(AzureVMAgentTemplate.java:1232)
		at com.microsoft.azure.vmagent.AzureVMCloud$1.call(AzureVMCloud.java:780)
		at com.microsoft.azure.vmagent.AzureVMCloud$1.call(AzureVMCloud.java:776)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.UnsupportedOperationException: Cannot create XMLStreamReader or XMLEventReader from a org.codehaus.stax2.io.Stax2ByteArraySource
	at com.sun.xml.internal.stream.XMLInputFactoryImpl.jaxpSourcetoXMLInputSource(XMLInputFactoryImpl.java:302)
	at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(XMLInputFactoryImpl.java:143)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:631)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:29)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1124)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3643)
	at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:281)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserializeBody(HttpResponseBodyDecoder.java:169)
	at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.lambda$decodeByteArray$0(HttpResponseBodyDecoder.java:82)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:259)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:401)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:416)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:470)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Caused: com.microsoft.azure.vmagent.exceptions.AzureCloudException
	at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:54)
	at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:33)
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.getCloudBlobContainer(AzureVMManagementServiceDelegate.java:2628)
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.getCloudBlobContainer(AzureVMManagementServiceDelegate.java:2645)
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.uploadCustomScript(AzureVMManagementServiceDelegate.java:863)
Caused: com.microsoft.azure.vmagent.exceptions.AzureCloudException: Failed to create Page Blob with script's length: 0
	at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:54)
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.uploadCustomScript(AzureVMManagementServiceDelegate.java:870)
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.createDeployment(AzureVMManagementServiceDelegate.java:516)
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.createDeployment(AzureVMManagementServiceDelegate.java:190)
	at com.microsoft.azure.vmagent.AzureVMAgentTemplate.provisionAgents(AzureVMAgentTemplate.java:1232)
	at com.microsoft.azure.vmagent.AzureVMCloud$1.call(AzureVMCloud.java:780)
	at com.microsoft.azure.vmagent.AzureVMCloud$1.call(AzureVMCloud.java:776)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jun 17, 2021 12:18:24 PM WARNING com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate createDeployment
AzureVMManagementServiceDelegate: deployment: Delete initScript failed: null```

Thank you for your help.

**Comment by camerenisonfire** [comment]
Here is the cloud section of our JCasC. We are using a custom image, which already has things like Java and Git installed, so the initScript is pretty simple. 

```
jenkins:  
  clouds:
    - azureVM:
        azureCredentialsId: "Azure-CycleAppliance"
        cloudName: "Azure"
        configurationStatus: "pass"
        deploymentTimeout: 1200
        existingResourceGroupName: "updated-jcasc"
        maxVirtualMachinesLimit: 10
        resourceGroupReferenceType: "existing"
        vmTemplates:
        - agentLaunchMethod: "JNLP"
          agentWorkspace: "c:\\jenkins"
          credentialsId: "agentadmin"
          diskType: "managed"
          doNotUseMachineIfInitFails: true
          enableMSI: false
          enableUAMI: false
          ephemeralOSDisk: false
          executeInitScriptAsRoot: false
          imageReference:
            offer: "cycleready2019"
            publisher: "tryonsolutionsinc1596650621083"
            sku: "winsrv19-cycle28"
            version: "latest"
          imageTopLevelType: "advanced"
          initScript: |
            # Setting IE Zoom level to 100
            $RegistryKeyPath_Zoom = "HKCU:\SOFTWARE\Microsoft\Internet Explorer\Zoom"
            Set-ItemProperty -Path $RegistryKeyPath_Zoom -Name ZoomFactor -Value 100000
            # Enabling IE protected mode for all zones
            $RegistryKeyPath_Zone1 = "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1"
            Set-ItemProperty -Path $RegistryKeyPath_Zone1 -Name 2500 -Value 0
            $RegistryKeyPath_Zone2 = "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2"
            Set-ItemProperty -Path $RegistryKeyPath_Zone2 -Name 2500 -Value 0
            $RegistryKeyPath_Zone3 = "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3"
            Set-ItemProperty -Path $RegistryKeyPath_Zone3 -Name 2500 -Value 0
            $RegistryKeyPath_Zone4 = "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4"
            Set-ItemProperty -Path $RegistryKeyPath_Zone4 -Name 2500 -Value 0
            # Adding IE trusted sites
            $RegistryKeyPath_TrustedSites = "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\Domains\my.cycleautomation.com"
            New-Item -Path $RegistryKeyPath_TrustedSites -ItemType Directory -Force
            New-ItemProperty -Path $RegistryKeyPath_TrustedSites -Name https -PropertyType DWORD -Value 2 -Force
            # Disable IE Enhanced Protected Mode
            $RegistryKeyPath_IEEnhanced = "HKCU:\SOFTWARE\Microsoft\Internet Explorer\Main"
            New-ItemProperty -Name "Isolation" -Path $RegistryKeyPath_IEEnhanced -Value "PMIL" -PropertyType String

            # Disable EnhSec
            $AdminKey = "HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}"
            $UserKey = "HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A8-37EF-4b3f-8CFC-4F3A74704073}"
            Set-ItemProperty -Path $AdminKey -Name "IsInstalled" -Value 0 -Force
            Set-ItemProperty -Path $UserKey -Name "IsInstalled" -Value 0 -Force
            Stop-Process -Name Explorer -Force
            Write-Host "IE Enhanced Security Configuration (ESC) has been disabled." -ForegroundColor Green

            # Disable IE welcome screen
            $RegistryKeyPath_IEWelcome = "HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Main"
            New-Item -Path $RegistryKeyPath_IEWelcome -ItemType Directory -Force
            New-ItemProperty -Path $RegistryKeyPath_IEWelcome -Name DisableFirstRunCustomize -PropertyType DWORD -Value 00000001 -Force

            # Configure Autologon
            $RegPath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"
            $DefaultUsername = "REDACTEDUSERNAME"
            $DefaultPassword = "REDACTEDPASSWORD"
            Set-ItemProperty $RegPath "AutoAdminLogon" -Value "1" -type String 
            Set-ItemProperty $RegPath "DefaultUsername" -Value "$DefaultUsername" -type String 
            Set-ItemProperty $RegPath "DefaultPassword" -Value "$DefaultPassword" -type String
            reg.exe ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Windows /v NoInteractiveServices /t REG_DWORD /d 0 /f

            # Install Slaves jar and connect via JNLP
            # Jenkins plugin will dynamically pass the server name and vm name.
            # If your jenkins server is configured for security , make sure to edit command for how slave executes
            $jenkinsserverurl = $args[0]
            $vmname = $args[1]
            $secret = $args[2]

            # Downloading jenkins slaves jar
            Write-Output "Downloading jenkins slave jar "
            mkdir c:\jenkins
            $slaveSource = $jenkinsserverurl + "jnlpJars/slave.jar"
            $destSource = "c:\jenkins\slave.jar"
            $wc = New-Object System.Net.WebClient
            $wc.DownloadFile($slaveSource, $destSource)

            # Download the bat boilerplate
            # Create the bat boilerplate file
            $batConfigFile = "c:\jenkins\jenkins-slave.bat"
            Add-Content -Path $batConfigFile -Value "`"@JAVA@`" @ARGS@"

            # Prepare bat file config
            Write-Output "Executing agent process "
            $javaHome = "c:\Program Files\Java\jdk1.8.0_131"
            $batConfigExec = "${javaHome}\bin\java.exe"
            $batConfigArgs = "-jar c:\jenkins\slave.jar -jnlpUrl `"${jenkinsserverurl}computer/${vmname}/slave-agent.jnlp`" -noReconnect"
            if ($secret) {
                $batConfigArgs += " -secret `"$secret`""
            }
            (Get-Content $batConfigFile).replace(''@JAVA@'', $batConfigExec) | Set-Content $batConfigFile
            (Get-Content $batConfigFile).replace(''@ARGS@'', $batConfigArgs) | Set-Content $batConfigFile

            # Put together scheduled task to launch the Jenkins agent via bat file at user login.
            $A = New-ScheduledTaskAction -Execute "c:\jenkins\jenkins-slave.bat"
            $T = New-ScheduledTaskTrigger -AtLogon
            $P = New-ScheduledTaskPrincipal "$env:COMPUTERNAME\agentadmin"
            $S = New-ScheduledTaskSettingsSet
            $D = New-ScheduledTask -Action $A -Principal $P -Trigger $T -Settings $S
            Register-ScheduledTask T1 -InputObject $D

            # Restart Temp Node
            Restart-Computer -Force
          installDocker: false
          installGit: false
          installMaven: false
          javaPath: "java"
          labels: "win19-cycleready"
          location: "East US 2"
          newStorageAccountName: "jnwgdvoq84jnrcgbhcprw5mw"
          noOfParallelJobs: 1
          nsgName: "cycleci-agent-nsg"
          osDiskSize: 0
          osDiskStorageAccountType: "StandardSSD_LRS"
          osType: "Windows"
          preInstallSsh: true
          retentionStrategy:
            azureVMCloudRetentionStrategy:
              idleTerminationMinutes: 60
          shutdownOnIdle: false
          storageAccountNameReferenceType: "new"
          storageAccountType: "Standard_LRS"
          subnetName: "cycleci-jenkins-subnet"
          templateDesc: "Custom Image POC"
          templateDisabled: false
          templateName: "win19-cycleready"
          usageMode: "Use this node as much as possible"
          usePrivateIP: true
          virtualMachineSize: "Standard_D4_v3"
          virtualNetworkName: "cycleci-azure-vnet"
          virtualNetworkResourceGroupName: "updated-jcasc"
```
We also tested this with a base image and got the same error.
          
  ```
  imageReference:
            offer: "WindowsServer"
            publisher: "MicrosoftWindowsServer"
            sku: "2016-Datacenter"
            version: "latest"
  ```
