### ISSUE TITLE
Jenkins cannot start Azure VM agents

### ISSUE THREAD

**Issue by wawrzek** [jenkinsci/azure-vm-agents-plugin#294]
### Version report

Jenkins and plugins versions report:
```
Jenkins: 2.289.2
OS: Linux - 5.4.0-1051-azure
---
sshd:3.0.3
persistent-parameter:1.3
display-url-api:2.3.5
kubernetes-client-api:5.4.1
cloudbees-bitbucket-branch-source:2.9.9
authentication-tokens:1.4
structs:1.23
blueocean-rest-impl:1.24.7
metrics:4.0.2.8
resource-disposer:0.16
workflow-cps-global-lib:2.21
pipeline-stage-tags-metadata:1.8.5
jquery3-api:3.6.0-2
token-macro:2.15
matrix-auth:2.6.7
configuration-as-code:1.51
data-tables-api:1.10.25-2
blueocean-core-js:1.24.7
validating-string-parameter:2.8
workflow-scm-step:2.13
saml:2.0.7
git-server:1.9
workflow-aggregator:2.6
pipeline-build-step:2.14
script-security:1.77
github-api:1.123
azure-sdk:25.vcde945b30f00
popper-api:1.16.1-2
workflow-basic-steps:2.23
pipeline-model-api:1.8.5
git-client:3.8.0
artifactory:3.12.4
lockable-resources:2.11
jdk-tool:1.0
command-launcher:1.2
pipeline-milestone-step:1.3.2
blueocean-config:1.24.7
blueocean-bitbucket-pipeline:1.24.7
plugin-util-api:2.4.0
pubsub-light:1.16
workflow-api:2.46
git:4.7.2
htmlpublisher:1.25
ivy:2.1
javadoc:1.6
branch-api:2.6.5
ssh-credentials:1.19
variant:1.4
trilead-api:1.0.13
workflow-job:2.41
blueocean-events:1.24.7
cloud-stats:0.27
workflow-support:3.8
workflow-multibranch:2.26
ant:1.11
bootstrap4-api:4.6.0-3
code-coverage-api:1.4.0
durable-task:1.38
blueocean-pipeline-scm-api:1.24.7
handlebars:3.0.8
docker-workflow:1.26
blueocean-dashboard:1.24.7
blueocean-jwt:1.24.7
sse-gateway:1.24
github-autostatus:3.6.2
jjwt-api:0.11.2-9.c8b45b8bb173
caffeine-api:2.9.1-23.v51c4e2c879c8
ansible:1.1
bouncycastle-api:2.20
pipeline-input-step:2.12
pipeline-stage-view:2.19
blueocean-autofavorite:1.2.4
blueocean-git-pipeline:1.24.7
azure-vm-agents:782.vb41dc00d85b1
blueocean:1.24.7
font-awesome-api:5.15.3-4
checks-api:1.7.2
echarts-api:5.1.2-3
github-branch-source:2.11.1
github:1.33.1
jsch:0.1.55.2
extended-read-permission:3.2
scm-api:2.6.4
gradle:1.37.1
snakeyaml-api:1.29.1
workflow-cps:2.93
jackson2-api:2.12.4
basic-branch-build-strategies:1.3.2
blueocean-commons:1.24.7
throttle-concurrents:2.3
credentials:2.5
pipeline-graph-analysis:1.11
blueocean-i18n:1.24.7
popper2-api:2.5.4-3
pipeline-model-extensions:1.8.5
mailer:1.34
workflow-durable-task-step:2.39
blueocean-github-pipeline:1.24.7
bootstrap5-api:5.0.2-1
blueocean-display-url:2.4.1
ace-editor:1.1
scm-filter-branch-pr:0.5
blueocean-rest:1.24.7
jacoco:3.3.0
kubernetes-credentials:0.9.0
credentials-binding:1.27
cloudbees-folder:6.15
forensics-api:1.2.1
pipeline-stage-step:2.5
cobertura:1.16
job-dsl:1.77
docker-commons:1.17
maven-plugin:3.12
blueocean-pipeline-editor:1.24.7
workflow-step-api:2.24
kubernetes:1.29.6
pipeline-rest-api:2.19
okhttp-api:3.14.9
kubernetes-credentials-provider:0.18-1
apache-httpcomponents-client-4-api:4.5.13-1.0
timestamper:1.13
role-strategy:3.1.1
handy-uri-templates-2-api:2.1.8-1.0
blueocean-pipeline-api-impl:1.24.7
blueocean-personalization:1.24.7
ws-cleanup:0.39
jenkins-design-language:1.24.7
ansicolor:1.0.0
momentjs:1.1.1
plain-credentials:1.7
pipeline-model-definition:1.8.5
azure-credentials:182.v3ccd4a755864
jobConfigHistory:2.28
junit:1.51
blueocean-web:1.24.7
config-file-provider:3.8.1
matrix-project:1.19
favorite:2.3.3
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins was installed by official Kubernetes Operator (version 0.6) via helm chart on an AKS cluster in azure.

### Reproduction steps

- set an Azure VM agent via UI. This is the config as a code representation of one of agents set is below.
```
  - azureVM:
      azureCredentialsId: "azure_sp_prodqa_ci102_azurevm"
      cloudName: "Azure-Shared"
      configurationStatus: "pass"
      deploymentTimeout: 1200
      maxVirtualMachinesLimit: 5
      newResourceGroupName: "SharedAgents"
      resourceGroupReferenceType: "new"
      vmTemplates:
      - agentLaunchMethod: "SSH"
        agentWorkspace: "/home/jenkins"
        builtInImage: "Ubuntu 20.04 LTS"
        credentialsId: "jenkins_agent_password"
        diskType: "managed"
        doNotUseMachineIfInitFails: true
        enableMSI: true
        enableUAMI: false
        ephemeralOSDisk: false
        executeInitScriptAsRoot: true
        existingStorageAccountName: "storageaccountname"
        imageReference:
          galleryImageDefinition: "Jenkins-Ubuntu1804"
          galleryImageVersion: "1.0.4"
          galleryName: "JenkinsAgents"
          galleryResourceGroup: "jenkins-images"
          gallerySubscriptionId: "3fb905f3-d113-4468-89fb-306de8222a37"
        imageTopLevelType: "advanced"
        installDocker: false
        installGit: false
        installMaven: false
        javaPath: "java"
        labels: "molecule vagrant shared docker packer molecule-vagrant packer-azure\
          \ molecule-test"
        location: "East US 2"
        maximumDeploymentSize: 5
        newStorageAccountName: "nameofstorageaccount"
        noOfParallelJobs: 1
        osDiskSize: 0
        osType: "Linux"
        preInstallSsh: true
        retentionStrategy:
          azureVMCloudRetentionStrategy:
            idleTerminationMinutes: 10
        shutdownOnIdle: false
        storageAccountNameReferenceType: "new"
        storageAccountType: "Standard_LRS"
        templateDesc: "Agents for Ansible and other projects"
        templateDisabled: false
        templateName: "azure-shared"
        usageMode: "Use this node as much as possible"
        usePrivateIP: false
        virtualMachineSize: "Standard_D2_v3"
```
- prepare a project to use the above label. This is a snippet of Jenkins file
```
                stages {
                    stage("Run molecule tests") {
                        agent {
                            node {
                                label 'molecule-vagrant'
                            }
                        }
```
- run a job.
### Results

Expected result:

Jobs are executed of VM

Actual result:

Agents are not started:
```
17:42:54  Still waiting to schedule task
17:42:54  Waiting for next available executor
17:42:54  Still waiting to schedule task
17:42:54  Waiting for next available executor
17:42:55  Still waiting to schedule task
17:42:55  Waiting for next available executor
```

There is no indication what's the problem is. Why the slaves cannot be started? It used to work with the same configuration, before Jenkins crash.

Where can I find more information about the problem? What kind of connectivity test I can run?
