### ISSUE TITLE
Agent does not connect (JCasC configuration) - java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "path" is null

### ISSUE THREAD

**Issue by BenjaminHerbert** [jenkinsci/azure-vm-agents-plugin#617]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.479.3
OS: Linux - 5.15.0-1075-azure
Java: 17.0.13 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
asm-api:9.7.1-97.v4cc844130d97
authentication-tokens:1.119.v50285141b_7e1
azure-credentials:343.vd80f9c4859df
azure-kubernetes-credentials:35.v0cefe6111a_b_4
azure-sdk:191.v53ec8913ee10
azure-vm-agents:975.va_a_d9b_6c912b_a_
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.79-254.vfdb_814e7791e
branch-api:2.1206.vd9f35001c95c
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.1
cloud-stats:336.v788e4055508b_
cloudbees-folder:6.976.v4dc79fb_c458d
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
configuration-as-code:1915.vcdd0a_d0d2625
copyartifact:761.vea_2b_25523e84
credentials:1405.vb_cda_74a_f8974
credentials-binding:687.v619cb_15e923f
display-url-api:2.209.v582ed814ff2f
docker-commons:445.v6b_646c962a_94
docker-workflow:580.vc0c340686b_54
durable-task:581.v299a_5609d767
echarts-api:5.5.1-5
eddsa-api:0.3.0-4.v84c6f0f4969e
font-awesome-api:6.6.0-2
git:5.7.0
git-client:6.1.0
gson-api:2.11.0-85.v1f4e87273c33
instance-identity:201.vd2a_b_5a_468a_a_6
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jacoco:3.3.7
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javax-activation-api:1.2.0-7
jaxb:2.3.9-1
job-dsl:1.90
joda-time-api:2.13.0-93.v9934da_29b_a_e9
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20241224-119.va_dca_a_b_ea_7da_5
junit:1312.v1a_235a_b_94a_31
kubernetes:4306.vc91e951ea_eb_d
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:190.v03c305394deb_
kubernetes-credentials-provider:1.262.v2670ef7ea_0c5
mailer:489.vd4b_25144138f
matrix-auth:3.2.3
matrix-project:840.v812f627cb_578
metrics:4.2.21-458.vcf496cb_839e4
mina-sshd-api-common:2.14.0-138.v6341ee58e1df
mina-sshd-api-core:2.14.0-138.v6341ee58e1df
oic-auth:4.444.vd4c54f157201
okhttp-api:4.11.0-183.va_87fc7a_89810
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:745.vdf6077913de0
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2218.v56d0cda_37c72
pipeline-model-definition:2.2218.v56d0cda_37c72
pipeline-model-extensions:2.2218.v56d0cda_37c72
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2218.v56d0cda_37c72
pipeline-stage-view:2.34
plain-credentials:183.va_de8f1dd5a_2b_
plugin-util-api:5.1.0
prism-api:1.29.0-18
resource-disposer:0.25
scm-api:698.v8e3b_c788f0a_6
script-security:1369.v9b_98a_4e95b_2d
simple-theme-plugin:196.v96d9592f4efa_
snakeyaml-api:2.3-123.v13484c65210a_
ssh-credentials:349.vb_8b_6b_9709f5b_
structs:338.v848422169819
trilead-api:2.147.vb_73cc728a_32e
uno-choice:2.8.6
variant:60.v7290fc0eb_b_cd
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:4007.vd705fc76a_34e
workflow-durable-task-step:1398.vf6c9e89e5988
workflow-job:1476.v90f02a_225559
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:936.v9fa_77211ca_e1
ws-cleanup:0.48
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller: Kubernetes via Jenkins Kubernetes Operator
Agent: ubuntu-24_04-lts

### Reproduction steps

1. Configure Jenkins with this JCasC clouds snippet:

```yaml
clouds:
  - azureVM:
      azureCredentialsId: "credentials-id"
      configurationStatus: "pass"
      deploymentTimeout: 1200
      existingResourceGroupName: "jenkins-agents"
      maxVirtualMachinesLimit: 10
      name: "azure"
      newResourceGroupName: "jenkins-agents"
      resourceGroupReferenceType: "existing"
      vmTemplates:
        - builtInImage: "Ubuntu 22.04 LTS"
          credentialsId: "vm-credentials"
          diskType: "managed"
          doNotUseMachineIfInitFails: true
          executeInitScriptAsRoot: true
          existingStorageAccountName: "storage-account"
          imageReference:
            offer: "ubuntu-lts"
            publisher: "Canonical"
            sku: "server"
            version: "latest"
          imageTopLevelType: "advanced"
          initScript: |-
             # Install Java
           apt-get -y update
           apt-get install -y default-jdk
             # some more

          installDocker: true
          installGit: true
          installMaven: true
          installQemu: true
          javaPath: "java"
          labels: "a-label"
          launcher: ssh
          licenseType: "Classic"
          location: "an-azure-location"
          maxVirtualMachinesLimit: 3
          maximumDeploymentSize: 10
          newStorageAccountName: "a-storage-account"
          noOfParallelJobs: 1
          osType: "Linux"
          retentionStrategy:
            azureVMCloudRetentionStrategy:
              idleTerminationMinutes: 60
          shutdownOnIdle: true
          storageAccountNameReferenceType: "new"
          storageAccountType: "Standard_LRS"
          subnetName: "subnet"
          templateDesc: "test agent"
          templateName: "agent-template"
          usageMode: NORMAL
          usePrivateIP: true
          virtualMachineSize: "Standard_B2s"
          virtualNetworkName: "a-vnet"
          virtualNetworkResourceGroupName: "a-vnet-rg"
```

2. Start a job using this agent.

### Expected Results

I expect the agent to launch, run the job and be fine.

### Actual Results

The agent does launch, but fails to connect.

This is in the logs:

```text

jenkins-master 2025-01-10 11:45:43.895+0000 [id=171]    INFO    c.m.azure.vmagent.AzureVMCloud#calculateNumberOfAgentsToRequest: Creating 1 nodes from template agent, currently have 0 VMs of this template, currently have 0 VMs in cloud
jenkins-master 2025-01-10 11:45:43.898+0000 [id=179]    INFO    c.m.a.v.AzureVMManagementServiceDelegate#createDeployment: Initializing deployment for 1 agentTemplate(s) agent
jenkins-master 2025-01-10 11:45:43.899+0000 [id=179]    INFO    c.m.a.v.AzureVMManagementServiceDelegate#createDeployment: Creating a new deployment agent0110114543899 with VM base name agentc5fb3 for 1 VM(s)
jenkins-master 2025-01-10 11:45:43.911+0000 [id=171]    INFO    c.m.azure.vmagent.AzureVMCloud#provision: 1 planned node(s)
jenkins-master 2025-01-10 11:45:44.226+0000 [id=179]    INFO    c.m.a.v.AzureVMManagementServiceDelegate#createDeployment: Use embedded deployment template (with managed) /referenceImageTemplateWithManagedDisk.json
jenkins-master 2025-01-10 11:45:47.815+0000 [id=184]    INFO    c.m.azure.vmagent.AzureVMCloud#createProvisionedAgent: Waiting for deployment agent0110114543899 with VM agentc5fb30 to be completed
jenkins-master 2025-01-10 11:46:04.630+0000 [id=184]    INFO    c.m.a.v.AzureVMManagementServiceDelegate#parseResponse: Deployment response: 
jenkins-master     found agent agentc5fb30
jenkins-master     OS type Linux
jenkins-master     number of executors 1
jenkins-master 2025-01-10 11:46:05.514+0000 [id=184]    INFO    c.m.a.v.AzureVMManagementServiceDelegate#setVirtualMachineDetails: The Azure agent doesn't have a public IP. Will use the private IP
jenkins-master 2025-01-10 11:46:05.516+0000 [id=184]    INFO    c.m.a.v.AzureVMCloudRetensionStrategy#start: Starting azureComputer agentc5fb30
jenkins-master 2025-01-10 11:46:05.749+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#getRemoteSession: Getting remote session for user jenkins to host 10.103.1.122:22
jenkins-master 2025-01-10 11:46:05.777+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#connectToSsh: Failed connecting to host 10.103.1.122:22. Will be trying again after 10 seconds, error was: java.net.ConnectException: Connection refused 
jenkins-master 2025-01-10 11:46:15.778+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#getRemoteSession: Getting remote session for user jenkins to host 10.103.1.122:22
jenkins-master 2025-01-10 11:46:16.547+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#getRemoteSession: Got remote session for user jenkins to host 10.103.1.122:22
jenkins-master 2025-01-10 11:46:16.547+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#executeRemoteCommand: Starting test -e ~/.azure-agent-init
jenkins-master 2025-01-10 11:46:29.572+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#executeRemoteCommand: Starting sh init.sh
jenkins-master 2025-01-10 11:48:35.233+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#getRemoteSession: Getting remote session for user jenkins to host 10.103.1.122:22
jenkins-master 2025-01-10 11:48:35.388+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#getRemoteSession: Got remote session for user jenkins to host 10.103.1.122:22
jenkins-master 2025-01-10 11:48:35.389+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#executeRemoteCommand: Starting touch ~/.azure-agent-init
jenkins-master 2025-01-10 11:48:35.835+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#executeRemoteCommand: Starting java -fullversion
jenkins-master 2025-01-10 11:48:45.880+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#launch: Launching agent agentc5fb30: java  -jar remoting.jar -workDir ~/remoting
jenkins-master 2025-01-10 11:48:45.881+0000 [id=171]    INFO    c.m.a.v.r.AzureVMAgentSSHLauncher#launch: Connected agentc5fb30 successfully
jenkins-master 2025-01-10 11:48:46.440+0000 [id=171]    SEVERE    c.m.a.v.r.AzureVMAgentSSHLauncher#launch: Got exception on agent agentc5fb30
jenkins-master java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "path" is null
jenkins-master     at hudson.Util.isRelativePath(Util.java:392)
jenkins-master     at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:703)
jenkins-master     at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:441)
jenkins-master     at PluginClassLoader for azure-vm-agents//com.microsoft.azure.vmagent.remote.AzureVMAgentSSHLauncher.launch(AzureVMAgentSSHLauncher.java:245)
jenkins-master     at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:297)
jenkins-master     at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
jenkins-master     at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
jenkins-master     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
jenkins-master     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jenkins-master     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jenkins-master     at java.base/java.lang.Thread.run(Unknown Source)
jenkins-master 2025-01-10 11:48:46.443+0000 [id=213]    INFO    h.r.SynchronousCommandTransport$ReaderThread#run: I/O error in channel agentc5fb30
jenkins-master java.io.EOFException
jenkins-master     at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
jenkins-master     at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
jenkins-master     at java.base/java.io.ObjectInputStream.readStreamHeader(Unknown Source)
jenkins-master     at java.base/java.io.ObjectInputStream.<init>(Unknown Source)
jenkins-master     at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:50)
jenkins-master     at hudson.remoting.Command.readFrom(Command.java:141)
jenkins-master     at hudson.remoting.Command.readFrom(Command.java:127)
jenkins-master     at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
jenkins-master     at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:62)
jenkins-master Caused: java.io.IOException: Unexpected termination of the channel
jenkins-master     at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:80)
jenkins-master 2025-01-10 11:48:46.452+0000 [id=184]    SEVERE    c.m.azure.vmagent.AzureVMCloud$2#call: Failure to in post-provisioning for 'agentc5fb30'
jenkins-master java.io.IOException: Agent failed to connect, even though the launcher didn't report it. See the log output for details.
jenkins-master     at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:325)
jenkins-master Caused: java.util.concurrent.ExecutionException
jenkins-master     at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
jenkins-master     at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
jenkins-master     at PluginClassLoader for azure-vm-agents//com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:885)
jenkins-master     at PluginClassLoader for azure-vm-agents//com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:837)
jenkins-master     at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
jenkins-master     at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
jenkins-master     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
jenkins-master     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jenkins-master     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jenkins-master     at java.base/java.lang.Thread.run(Unknown Source)
jenkins-master 2025-01-10 11:48:46.453+0000 [id=184]    INFO    c.m.a.v.AzureVMManagementServiceDelegate#virtualMachineExists: Checking VM exists for agentc5fb30
jenkins-master 2025-01-10 11:48:46.458+0000 [id=214]    INFO    hudson.remoting.Request$2#run: Failed to send back a reply to the request UserRequest:UserRPCRequest:hudson.remoting.JarLoader.writeJarTo[long,long,java.io.OutputStream](3): hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@7fea301c:agentc5fb30": channel is already closed
jenkins-master 2025-01-10 11:48:46.868+0000 [id=184]    INFO    c.m.a.v.AzureVMManagementServiceDelegate#terminateVirtualMachine: Removing virtual machine agentc5fb30
jenkins-master 2025-01-10 11:49:57.836+0000 [id=184]    INFO    c.m.a.v.AzureVMManagementServiceDelegate#terminateVirtualMachine: Removing managed disk with id: /subscriptions/xxxxxxx-yyyyy-zzzz-9375-8afa54e0c2f9/resourceGroups/jenkins-agents/providers/Microsoft.Compute/disks/agentc5fb30_disk1_02e7c2c29b7d4f6f804f346342f21910
```

### Anything else?

It seems that validating the template once fixes the issue and the agent can then be launched. I would expect to be able to use JCasC to configure a working configuration without manual steps after launch.

### Are you interested in contributing a fix?

Not sure I would be able to.
