### ISSUE TITLE
Incorrect vnet assignment

### ISSUE THREAD

**Issue by igor-teresco** [jenkinsci/azure-vm-agents-plugin#623]
I'm trying to create agent VMs in azure in a dedicated vnet to be used by Jenkins master over private IP.
VM template looks like this in JCasC:
```
- azureVM:
      azureCredentialsId: "service_principal_dev_creds"
      cloudTags:
      - name: "jenkins"
        value: "agent"
      configurationStatus: "pass"
      deploymentTimeout: 1200
      existingResourceGroupName: "jenkins-vault-1-rg"
      maxVirtualMachinesLimit: 10
      name: "Azure VMs"
      resourceGroupReferenceType: "existing"
      vmTemplates:
      - acceleratedNetworking: true
        availabilityType: "none"
        builtInImage: "Ubuntu 24.04 LTS"
        credentialsId: "azure-admin"
        diskType: "managed"
        doNotUseMachineIfInitFails: true
        enableUAMI: true
        executeInitScriptAsRoot: true
        existingStorageAccountName: "jenkinsvault1rg33f2"
        imageReference:
          version: "latest"
        imageTopLevelType: "basic"
        installDocker: true
        installGit: true
        installMaven: true
        javaPath: "java"
        labels: "azure-agent"
        licenseType: "None"
        location: "Germany West Central"
        maximumDeploymentSize: 10
        newStorageAccountName: "jenkinsvault1rgagents"
        noOfParallelJobs: 1
        nodeProperties:
        - diskSpaceMonitor:
            freeDiskSpaceThreshold: "1GiB"
            freeDiskSpaceWarningThreshold: "2GiB"
            freeTempSpaceThreshold: "1GiB"
            freeTempSpaceWarningThreshold: "2GiB"
        nsgName: "jenkins-aks-nsg"
        osDiskStorageAccountType: "Premium_LRS"
        osType: "Linux"
        retentionStrategy:
          azureVMCloudRetentionStrategy:
            idleTerminationMinutes: 60
        storageAccountNameReferenceType: "existing"
        storageAccountType: "Standard_LRS"
        subnetName: "aks-subnet"
        templateDesc: "Gradle build agent"
        templateName: "gradle"
        uamiID: "/subscriptions/{our-sub-id}/resourcegroups/MC_jenkins-vault-1-rg_jenkins-aks-1_germanywestcentral/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jenkins-aks-1-agentpool"
        usageMode: EXCLUSIVE
        useEntraIdForStorageAccount: true
        usePrivateIP: true
        virtualMachineSize: "Standard_B20ms"
        virtualNetworkName: "spoke1-kubevnet"
        virtualNetworkResourceGroupName: "jenkins-vault-1-rg"
```
VMs are getting created in proper RG but in some new created vnet/subnet (jenkinsarm-vnet / jenkinsarm-snet)...
Template is validated correct, if I make a mistake in vnet name, verification fails with proper error.

Please advise what else I can check?
